---
- hosts: all
  become: yes

  tasks:
  - name: Установка Zabbix агента на Ubuntu
    apt: pkg={{ item }} state=latest
    with_items:
      - zabbix-agent
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    notify:
        zabbix-agent systemd
        
  - name: Install zabbix repo.
    command: "rpm -ivh https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm"
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    notify:
        zabbix-agent systemd

  - name: Установка Zabbix агента на Centos
    yum: pkg={{ item }} state=latest
    with_items:
      - zabbix-agent
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  
  - name: Reconfigure zabbix-agent
    lineinfile:
     dest: /etc/zabbix/zabbix_agentd.conf
     regexp: "^ServerActive=127.0.0.1"
     line: "ServerActive=10.128.0.36"
     state: present

  - name: Reconfigure zabbix-agent 
    lineinfile:
     dest: /etc/zabbix/zabbix_agentd.conf
     regexp: "^Server=127.0.0.1"
     line: "Server=10.128.0.36"
     state: present

  - name: Reconfigure zabbix-agent
    lineinfile:
     dest: /etc/zabbix/zabbix_agentd.conf
     regexp: "Hostname=Zabbix server"
     line: "Hostname={{ ansible_hostname }}"
     state: present
   
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
